permalink: none

domain: www.avtobiografia.com
title: Evgeniy Vasilev
author: aquilax
email: aquilax@gmail.com

tag_title_prefix: 'Projects tagged &ldquo;'

google_analytics:
  account: UA-115818-51

