permalink: none

domain: www.avtobiografia.com
title: Evgeniy Vasilev
author: aquilax
email: aquilax@gmail.com

google_analytics:
  account: UA-115818-51

mini_magick:
  normal:
    source: original_images/
    destination: img/
    resize: "584x600"
